### ISSUE TITLE
Wish to Nginx

### ISSUE THREAD

**Issue by T-Shilov** [qvarforth/trackdirect#17]
Hi, Per,

Sorry for modest wish: If possible, remake your wonderful project to use Nginx.
You know perfectly well that Nginx works much faster than Apache and uses less memory.

**Comment by qvarforth** [comment]
Hi,

You are very welcome to use nginx instead of apache, the readme is just an example on how you can do it. I use nginx as a reverse proxy infront of the apache server, but I still prefer apache for serving dynamic content.

The performance for a website such as this is very little affected by the loading time. The database and he websocket server python code has far greater affect on the performance.

I'm closing this issue since it is out of scope, but as I said, your are very welcome to try it yourself. If you find out that any changes are required to use nginx for serving php content you are very welcome to fork the project and create a pull request.. or just keep it in your own fork.
